{
 "title": "LiveKit Server Monitoring - Enhanced",
 "tags": [
  "livekit",
  "sim-meet"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(namespace)" } },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   { "name": "node_id", "label": "node_id", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  {
   "title": "Packet bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "livekit_packet_bytes{namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Participants Joined",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(livekit_participant_join_total{namespace=\"$namespace\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Rooms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_room_total{namespace=\"$namespace\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_participant_total{namespace=\"$namespace\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Publishers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_track_publish_counter{namespace=~\"$namespace\", job=~\"$job\", kind=~\"AUDIO\", node_id=~\"$node_id\", node_type=~\"SERVER\", state=~\"success\"}",
     "legendFormat": "Audio Publishers"
    },
    {
     "expr": "livekit_track_publish_counter{namespace=~\"$namespace\", job=~\"$job\", kind=~\"VIDEO\", node_id=~\"$node_id\", node_type=~\"SERVER\", state=~\"success\"}",
     "legendFormat": "Video Publishers"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "LiveKit CPU Time"
    },
    {
     "expr": "process_cpu_seconds_total{instance=\"localhost:9090\", job=\"prometheus\"}",
     "legendFormat": "Prometheus CPU Time"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", job=~\"$job\"}",
     "legendFormat": "LiveKit Memory Usage"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"localhost:9090\", job=\"prometheus\"}",
     "legendFormat": "Prometheus Memory Usage"
    }
   ]
  },
  {
   "title": "Total Subscribed Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_track_subscribed_total{namespace=\"$namespace\", job=~\"$job\", kind=~\"AUDIO\", node_id=~\"$node_id\", node_type=~\"SERVER\"}",
     "legendFormat": "Audio Subscribed Tracks"
    },
    {
     "expr": "livekit_track_subscribed_total{instance=~\"$instance\", job=~\"$job\", kind=~\"VIDEO\", node_id=~\"$node_id\", node_type=~\"SERVER\"}",
     "legendFormat": "Video Subscribed Tracks"
    }
   ]
  },
  {
   "title": "Total Subscribers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_track_subscribe_counter{namespace=\"$namespace\", state=~\"success\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total Published Tracks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_track_published_total{namespace=\"$namespace\", job=~\"$job\", kind=~\"AUDIO\", node_id=~\"$node_id\", node_type=~\"SERVER\"}",
     "legendFormat": "Audio Published Tracks"
    },
    {
     "expr": "livekit_track_published_total{instance=~\"$instance\", job=~\"$job\", kind=~\"VIDEO\", node_id=~\"$node_id\", node_type=~\"SERVER\"}",
     "legendFormat": "Video Published Tracks"
    }
   ]
  },
  {
   "title": "Quality Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_quality_score_sum / livekit_quality_score_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Quality Parameters",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "livekit_quality_rating_bucket{namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}