{{- if .Values.global.egress.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "egress.serviceAccountName" . }}
  labels:
    {{- include "egress.labels" . | nindent 4 }}
  {{- with .Values.global.egress.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
