apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey-livekit-deployment
  labels:
    {{- include "livekit.valkey.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "livekit.valkey.labels" . | nindent 6 }}
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-valkey.yaml") . | sha256sum }}
      labels:
        {{- include "livekit.valkey.labels" . | nindent 8 }}
    spec:
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
      {{- range $pullSecret := .Values.global.imagePullSecrets }}
        - name: {{ $pullSecret.name }}
      {{- end }}
      {{- end }}
      containers:
      - name: master
        image: "{{ .Values.image.registry }}{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: valkey-secrets
                key: password
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
        readinessProbe:
          exec:
            command:
              - sh
              - -c
              - "valkey-cli -h localhost ping"
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - "valkey-cli -h localhost ping"
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - name: app
          containerPort: {{ .Values.appPort }}
          protocol : TCP
        volumeMounts:
          - name: valkeyconfig
            mountPath: /usr/local/etc/valkey
      volumes:
        - name: valkeyconfig
          configMap:
            name: valkey-livekit-config
      {{- with .Values.global.livekit.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.livekit.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
