apiVersion: v1
kind: Service
metadata:
  name: valkey-livekit-service
  labels:
    {{- include "livekit.valkey.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.appPort }}
    targetPort: {{ .Values.appPort }}
  selector:
    {{- include "livekit.valkey.labels" . | nindent 4 }}
