{{- if .Values.global.meet_agent.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "meet-agent.serviceAccountName" . }}
  labels:
    {{- include "meet-agent.labels" . | nindent 4 }}
  {{- with .Values.global.meet_agent.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
