apiVersion: v1
kind: Service
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- with .Values.global.livekit.loadBalancer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.global.livekit.loadBalancer.servicePort }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.global.livekit.config.rtc.tcp_port }}
    - name: rtc-tcp
      port: {{ .Values.global.livekit.config.rtc.tcp_port }}
      protocol: TCP
      targetPort: rtc-tcp
    {{- end }}
    {{- if .Values.global.livekit.config.rtc.udp_port }}
    - name: rtc-udp
      port: {{ .Values.global.livekit.config.rtc.udp_port }}
      protocol: UDP
      targetPort: rtc-udp
    {{- end }}

    {{- if .Values.global.livekit.config.prometheus_port }}
    - port: {{ .Values.global.livekit.config.prometheus_port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
    {{- end }}
    
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
