{{- if .Values.global.livekit.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "livekit-server.serviceAccountName" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- with .Values.global.livekit.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
